# Site settings
title: KMS Portfolio
email: kms2786210@naver.com
url: https://kms6210.github.io/
description: "Thank you for visiting my portfolio! 👋 <br>
🌱 I’m currently learning Computer Science and Engineering at Seoul National University. <br>
📚 I’m majoring in Civil and Environment Engineering at SNU, and will graduate soon. <br>
💬 How to reach me: kms2786210@naver.com"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
